### ISSUE TITLE
snowc has a problem - The error was: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by panthersdude2001** [panthersdude2001/WCT-Timer#6]
The user snowc on computer BRYCE-PC, has encountered an error when using the program. The following details follows.
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at WCT_Timer.MainFormLAG.FrmLAG_Load(Object sender, EventArgs e) in C:\Users\snowc\source\repos\WDLCT2\WDLCT 3.5\Wildcat All-In-One Timer\MainFormLAG.vb:line 146
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Please tell snowc how to fix this error.
Thanks.
snowc

**Comment by panthersdude2001** [comment]
Closing as this is the last test
